### ISSUE TITLE
Can't Find the Model in the Provided File

### ISSUE THREAD

**Issue by ethankim-00** [HansiZeng/CL-DRD#1]

**Comment by HansiZeng** [comment]
I can download it from https://drive.google.com/file/d/1aC0-RSB6MU9v65OK1eh8yItyeG_nGQGU/view. Can you double-check it or give me a more specific thing, such as a screenshot of the issue you encounter?

**Comment by ethankim-00** [comment]
Apologies if I'm missing something: I don't find the model of extracting that file
![image](https://user-images.githubusercontent.com/95236428/205139289-a43ff484-99bb-42cc-9a60-7ee166aa961f.png)

**Comment by HansiZeng** [comment]
You don't need to uncompress the model. If you really need to do it, uncompress it by using python code: 
``` data = torch.load(path_to_the_tar_file)```.

To index the model, run the command line below ("path/to/pretrained/model" is the path of your tar file which should have the name "checkpoint_120000.pth.tar")
```
python retriever/index_text.py --resume="path/to/pretrained/model" --passages_path="path/to/msmarco/collection.tsv" --index_dir="path/to/index_dir/"
```
